name: ZCLI template

# Triggers the workflow...
on:
  # ...when you push...
  push:
    # ...to branch "main" 
    branches: [main]
  # ...when you manually click "Run Workflow" on GitHub from the Actions page  
  workflow_dispatch:

# If the worflow is triggered by one of the above options...

# ...jobs will kick off to...
jobs:
  # ...create a build using...
  build:
    # ...the latest version of Ubuntu...
    runs-on: ubuntu-latest
    # ...using Node version 23.x...
    strategy:
      matrix:
        node-version: [23.x]

    #...and these authentication details, which are pulled from your Actions secrets    
    env:
      ZENDESK_SUBDOMAIN: ${{  secrets.SUBDOMAIN  }}
      ZENDESK_EMAIL: ${{  secrets.EMAIL  }}
      ZENDESK_API_TOKEN: ${{  secrets.API_TOKEN  }}

    # With the environment setup, we can begin taking action...
    
    steps:
      # Default Node.js workflow...
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Uncomment the next line only when using React
          # cache: 'npm'
      # ...install the Zendesk CLI
      - name: Install zcli
        run: npm i @zendesk/zcli -g
      # These next three actions will run if the commit message contains the word in each 'if' condition. If your commit message contains all three words, each action will run. Basically, don't use this workflow in a production environment!
      - name: Bump patch version 
        if: contains(github.event.head_commit.message, 'patch')
        run: zcli apps:bump -p
      - name: Bump minor version
        if: contains(github.event.head_commit.message, 'minor')
        run: zcli apps:bump -m
      - name: Bump major version 
        if: contains(github.event.head_commit.message, 'major')
        run: zcli apps:bump -M
      # Finally, we need to push the changes to our repository. Since GitHub Actions run in a separate environment, the above changes won't update your repo without this.
      - name: Update repo 
        run: |
             git config --global user.email "[your GH email]"
             git config --global user.name "[your name]"
             
             git add -A
             git commit -m "Commit message
             git push